### ISSUE TITLE
Probably not supported status 'cancelled' for 'neuro logs'

### ISSUE THREAD

**Issue by yartem** [neuromation/platform-client-python#1727]
See error in `neuro logs` command
```
$ n status job-af800a8e-4542-4071-baa5-24c017824995
Job: job-af800a8e-4542-4071-baa5-24c017824995
Name: jupyter-test-project-be12140b
Tags: build-4378, kind:project, project-id:neuro-project-54e762df, project:test-project-be12140b, target:jupyter
Owner: cookiecutter-e2e
Cluster: neuro-public
Status: cancelled
Image: image:cookiecutter-e2e:be12140b
Command: jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token= --notebook-dir=/project/notebooks
Resources:
  Memory: 57.0G
  CPU: 3.0
  GPU: 1.0 x nvidia-tesla-k80
  Additional: Extended SHM space
Life span: 1h
TTY: True
Volumes:
  /project/modules    storage:test-project-be12140b/modules            
  /project/config     storage:test-project-be12140b/config     READONLY
  /project/data       storage:test-project-be12140b/data       READONLY
  /project/results    storage:test-project-be12140b/results            
  /project/notebooks  storage:test-project-be12140b/notebooks          
Internal Hostname: job-af800a8e-4542-4071-baa5-24c017824995.platform-jobs
Internal Hostname Named: jupyter-test-project-be12140b--cookiecutter-e2e.platform-jobs
Http URL: https://jupyter-test-project-be12140b--cookiecutter-e2e.jobs.neuro-public.org.neu.ro
Http port: 8888
Http authentication: False
Environment:
  PYTHONPATH=/project
Created: 2020-09-09T01:09:51.022141+00:00
Started: 2020-09-09T01:10:00.933746+00:00
Finished: 2020-09-09T01:10:00.933746+00:00
Exit code: None

$ n logs job-af800a8e-4542-4071-baa5-24c017824995    # <-- error here
ERROR: Illegal argument(s) ('cancelled' is not a valid JobStatus)

$ n config show
User Configuration:
  User Name: cookiecutter-e2e
  Current Cluster: neuro-public
...

$ n --version
Neuro Platform Client 20.9.3
```

**Comment by serhiy-storchaka** [comment]
Is it reproduced today? It should be fixed after deploying the last platform-monitoring (updated yersterday). @zubenkoivan

**Comment by YevheniiSemendiak** [comment]
@serhiy-storchaka,
Yes, it is still reproducible
![image](https://user-images.githubusercontent.com/32543098/93061181-e1ec6e00-f67b-11ea-8304-523872411fdf.png)

**Comment by zubenkoivan** [comment]
@YevheniiSemendiak @serhiy-storchaka It was fixed in monitoring service but haven't been deployed yet. Should be ok in dev

**Comment by zubenkoivan** [comment]
I just have deployed the last version. Please check once again

**Comment by YevheniiSemendiak** [comment]
I do not see the problem anymore.
I guess we may close the issue if all is OK at @yartem's case.
